# numpy

In [1]:
a=[1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


### numpy套件的ndarray型態，提供element-wise的操作

In [31]:
import numpy as np
b = np.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


In [30]:
print(type(b))
print(b.ndim)
print(b.shape)
print(b.dtype)

<class 'numpy.ndarray'>
1
(5,)
int32


In [29]:
print(np.zeros(6))
print(np.zeros((3,6)))
print(np.zeros((2,3,6)))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [32]:
a=np.zeros(16)
print(a)
print(a.shape)
b=a.reshape((4,4))
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


In [33]:
my_array = np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [37]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b=np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c=np.array(np.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [1]:
import numpy as np
my_2d_array=np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:])
print(my_2d_array[1,])
print(my_2d_array[:,0])
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6


### 假設有六個組別"Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"
### 其參加人數分別為56, 8, 19, 14, 6, 71人

In [3]:
import numpy as np
groups = ["modern web","Devops","cloud","big data","security","自我挑戰組"]
iron=[56,8,19,14,6,71]
groups_array = np.array(groups)
iron_array = np.array(iron)
print(groups_array)
print(iron_array)

['modern web' 'Devops' 'cloud' 'big data' 'security' '自我挑戰組']
[56  8 19 14  6 71]


In [4]:
print(iron_array >= 10)
print(groups_array[iron_array>=10])

[ True False  True  True False  True]
['modern web' 'cloud' 'big data' '自我挑戰組']


In [5]:
print(groups_array !="自我挑戰組")
print(iron_array[groups_array !="自我挑戰組"])

[ True  True  True  True  True False]
[56  8 19 14  6]


In [6]:
nan_array = np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


In [7]:
uniform_samples=np.random.uniform(size=10)
print(uniform_samples)

[0.17787749 0.04768765 0.64479491 0.3296548  0.82788191 0.40939678
 0.47480076 0.53473202 0.13380018 0.23279496]
